export enum E_SessionStore {
    storeSessionContent = 'storeSessionContent',
    storeSessionContentPages = 'storeSessionContentPages',
    storeSessionContentStartTimer = 'storeSessionContentStartTimer',
    storeSessionContentQuestionReceivedAnswers = 'storeSessionContentQuestionReceivedAnswers',
    storeSessionContentUpdateTimer = 'storeSessionContentUpdateTimer',
    storeSessionContentShowAnswer = 'storeSessionContentShowAnswer',
    storeSessionContentQuestionAnswerYesNo = 'storeSessionContentQuestionAnswerYesNo',
    storeSessionContentAnswersMultipleAnswers = 'storeSessionContentAnswersMultipleAnswers',
    storeSessionContentQuestionAnswersSelectImage = 'storeSessionContentQuestionAnswersSelectImage',
    storeSessionContentStart = 'storeSessionContentStart',
    storeSessionContentQuestionRemainingTime = 'storeSessionContentQuestionRemainingTime',
    storeSessionContentQuestionAnswerDraggingAnswer = 'storeSessionContentQuestionAnswerDraggingAnswer',
    storeSessionContentCodes = 'storeSessionContentCodes',
    storeSessionContentAnswerQuestionYesNo = 'storeSessionContentAnswerQuestionYesNo',
    storeHideAnswerGet = 'storeHideAnswerGet',
    storeSessionContentShowAnswerGet = 'storeSessionContentShowAnswerGet',
    storeSessionContentAnswerQuestionMultipleAnswer = 'storeSessionContentAnswerQuestionMultipleAnswer',
    storeSessionContentAnswerQuestionSelectImage = 'storeSessionContentAnswerQuestionSelectImage',
    storeSessionContentRegisterPartecipant = 'storeSessionContentRegisterPartecipant',
    storeSessionContentAnswerQuestionDraggingAnswer = 'storeSessionContentAnswerQuestionDraggingAnswer',
    storeSessionContentQuestionAnswerSent = 'storeSessionContentQuestionAnswerSent',
    storeSessionContentRepository = 'storeSessionContentRepository',
}